name: diauxic-metabol
channels:
  - conda-forge
dependencies:
  - python=3.11
  # CookieCutter for Data Science packages
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm

  - numpy
  - scipy
  - pandas
  - matplotlib
  - tensorflow
  - cobra

  - pip:
    - python-dotenv
    - mkdocs
    - -e .